name: solar-system CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v6
      - name: Setup NodeJS version - 18
        uses: actions/setup-node@v6
        with:
          node-version: '18'
      - name: Cache dependencies        ## Cache dependencies 
        uses: actions/cache@v5
        with:
            path: node_modules
            key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Unit testing
        id: unit-test-id        # giving this step an unique name
        run: npm test
      - name: Archive test result
        # if: ${{ steps.unit-test-id.outcome == 'failure' || steps.unit-test-id.outcome == 'success' }}
        # if: ${{ failure() && (steps.unit-test-id.outcome == 'failure' || steps.unit-test-id.outcome == 'success') }}    # it will skip the step if the previous step is success.
        if: ${{ always()}}      # this step should always run

        uses: actions/upload-artifact@v7
        with:
          name: Unit-test-result
          path: test-results.xml

  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    # continue-on-error: true     # we can add this in job level to prevent the workflow from failure
    steps:
      - name: checkout the repo
        uses: actions/checkout@v6
      - name: Setup NodeJS version - 18
        uses: actions/setup-node@v6
        with:
          node-version: '18'
      - name: Cache dependencies        ## Cache dependencies 
        uses: actions/cache@v5
        with:
            path: node_modules
            key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Check code coverage
        continue-on-error: true     # adding this in step level to prevent the job from failure
        run: npm run coverage
      - name: Archive test result
        uses: actions/upload-artifact@v7
        with:
          name: Code-Coverage-Result
          path: coverage
          retention-days: 3
            
  docker:
    name: Containerization
    runs-on: ubuntu-latest
    needs:
      - unit-testing
      - code-coverage
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: docker Hub login
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: GHCR login                  # Multiple registry. for example ghcr.io
        uses: docker/login-action@v4
        with:
          registry: 'ghcr.io'
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build for testing
        uses: docker/build-push-action@v7
        with:
          context: "."       # path where Dockerfile resides.
          push: false        # Don't want to push now
          tags: ${{ vars.DOCKERHUB_REPO }}/solar-system:${{ github.sha }}

      - name: Docker Image testing
        run: |
          docker images
          docker run --name solar-system-app -d \
              -p 3000:3000 \
              -e MONGO_URI=$MONGO_URI \
              -e MONGO_USERNAME=$MONGO_USERNAME \
              -e MONGO_PASSWORD=$MONGO_PASSWORD \
              ${{ vars.DOCKERHUB_REPO }}/solar-system:${{ github.sha }}

              ### just to test. Not actually using this

              # export IP=$(docker inspect -f '{{ range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
              export IP=$(docker inspect -f '{{.NetworkSettings.Networks.bridge.IPAddress}}' solar-system-app)
              echo $IP
              wget -q -O - 127.0.0.1:3000/live | grep live

      - name: Docker push to dockerhub registry and ghcr 
        uses: docker/build-push-action@v7
        with:
          context: "."
          push: true
          # To push to dockerhub and to ghcr
          tags: |
            ${{ vars.DOCKERHUB_REPO }}/solar-system:${{ github.sha }}
            ghcr.io/arupgithubb/solar-system:${{ github.sha }}
